apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
spec:
  replicas: {{ .Values.replicaCount.client }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.client.repository }}:{{ .Values.image.client.tag }}"
          imagePullPolicy: {{ .Values.image.client.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.client.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - port: {{ .Values.service.client.port }}
      targetPort: {{ .Values.service.client.port }}
  selector:
    app: {{ .Release.Name }}-client
